/**
 * Advanced Export Utilities
 * - Google Sheets compatible CSV
 * - Webhook POST with signature
 * - JSON export
 */

/**
 * Generate a simple HMAC-like signature for webhook payloads
 * Using a basic hash since we can't use crypto in browser without polyfills
 */
export function generateSignature(payload: string, timestamp: number): string {
    // Simple hash function for signature (browser-compatible)
    let hash = 0
    const str = `${timestamp}.${payload}`
    for (let i = 0; i < str.length; i++) {
        const char = str.charCodeAt(i)
        hash = ((hash << 5) - hash) + char
        hash = hash & hash // Convert to 32bit integer
    }
    return `sha256=${Math.abs(hash).toString(16)}`
}

/**
 * Generate Google Sheets compatible CSV with BOM for proper UTF-8 handling
 */
export function generateSheetsCompatibleCSV(
    rows: Array<{ mappedData: Record<string, string> }>,
    fieldNames: string[]
): string {
    const BOM = '\uFEFF'

    const escapeField = (value: string): string => {
        if (!value) return ''
        // Escape quotes and wrap in quotes if contains special chars
        if (value.includes(',') || value.includes('"') || value.includes('\n') || value.includes('\r')) {
            return `"${value.replace(/"/g, '""')}"`
        }
        return value
    }

    const header = fieldNames.map(escapeField).join(',')
    const dataRows = rows.map(row =>
        fieldNames.map(field => escapeField(row.mappedData[field] || '')).join(',')
    )

    return BOM + header + '\r\n' + dataRows.join('\r\n')
}

/**
 * Convert rows to JSON array for webhook
 */
export function rowsToJSON(
    rows: Array<{ mappedData: Record<string, string> }>,
    fieldNames: string[]
): Record<string, unknown>[] {
    return rows.map(row => {
        const obj: Record<string, unknown> = {}
        for (const field of fieldNames) {
            obj[field] = row.mappedData[field] || ''
        }
        return obj
    })
}

/**
 * Send data to webhook URL
 */
export async function sendToWebhook(
    url: string,
    data: object[],
    options: {
        includeMetadata?: boolean
        fileName?: string
    } = {}
): Promise<{ success: boolean; message: string; statusCode?: number }> {
    const timestamp = Date.now()

    const payload = {
        data,
        metadata: options.includeMetadata ? {
            exported_at: new Date().toISOString(),
            row_count: data.length,
            source: 'CSV Import Copilot',
            file_name: options.fileName || 'unknown',
        } : undefined,
    }

    const payloadString = JSON.stringify(payload)
    const signature = generateSignature(payloadString, timestamp)

    try {
        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-Webhook-Timestamp': timestamp.toString(),
                'X-Webhook-Signature': signature,
                'User-Agent': 'CSV-Import-Copilot/1.0',
            },
            body: payloadString,
        })

        if (response.ok) {
            return {
                success: true,
                message: `Successfully sent ${data.length} rows`,
                statusCode: response.status,
            }
        } else {
            return {
                success: false,
                message: `Webhook returned ${response.status}: ${response.statusText}`,
                statusCode: response.status,
            }
        }
    } catch (error) {
        return {
            success: false,
            message: error instanceof Error ? error.message : 'Network error',
        }
    }
}

/**
 * Google Apps Script template for importing CSV
 */
export const GOOGLE_APPS_SCRIPT_TEMPLATE = `/**
 * CSV Import Script for Google Sheets
 * Generated by CSV Import Copilot
 * 
 * Instructions:
 * 1. Open your Google Sheet
 * 2. Go to Extensions > Apps Script
 * 3. Paste this code and save
 * 4. Run importCSVFromURL() or uploadCSV()
 */

// Option 1: Import from a URL (if CSV is hosted somewhere)
function importCSVFromURL() {
  const csvUrl = 'YOUR_CSV_URL_HERE';
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
  
  try {
    const response = UrlFetchApp.fetch(csvUrl);
    const csvData = Utilities.parseCsv(response.getContentText());
    
    // Clear existing data
    sheet.clear();
    
    // Write new data
    if (csvData.length > 0) {
      sheet.getRange(1, 1, csvData.length, csvData[0].length).setValues(csvData);
      
      // Format header row
      sheet.getRange(1, 1, 1, csvData[0].length)
        .setFontWeight('bold')
        .setBackground('#f3f3f3');
      
      SpreadsheetApp.getUi().alert('Success! Imported ' + (csvData.length - 1) + ' rows.');
    }
  } catch (e) {
    SpreadsheetApp.getUi().alert('Error: ' + e.message);
  }
}

// Option 2: Parse CSV data directly (paste your CSV content)
function importCSVDirect() {
  const csvContent = \`
YOUR_CSV_CONTENT_HERE
\`;
  
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
  const csvData = Utilities.parseCsv(csvContent.trim());
  
  sheet.clear();
  
  if (csvData.length > 0) {
    sheet.getRange(1, 1, csvData.length, csvData[0].length).setValues(csvData);
    sheet.getRange(1, 1, 1, csvData[0].length)
      .setFontWeight('bold')
      .setBackground('#f3f3f3');
  }
}

// Option 3: Create a custom menu
function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('CSV Importer')
    .addItem('Import from URL', 'importCSVFromURL')
    .addItem('Import Direct', 'importCSVDirect')
    .addToUi();
}
`;

/**
 * Download helper
 */
export function downloadFile(content: string, filename: string, mimeType: string): void {
    const blob = new Blob([content], { type: mimeType })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = filename
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
}
